'use client';
import { useState, useEffect, useRef } from 'react';
import { useSession } from '@/app/components/SessionContext';
import { createSupabaseClient } from '@/lib/supabase';
import { Loader2, Sparkles, ChevronRight, CheckCircle2 } from 'lucide-react';

export default function SessionStep2Ideas() {
    const { state, dispatch, completeStep } = useSession();
    const {
        brain, contentPillars, sessionFAQs, timeHorizon,
        generatedIdeas, selectedSlotIds, projectId, sessionId,
    } = state;
    const supabase = createSupabaseClient();

    const [loading, setLoading]     = useState(false);
    const [error, setError]         = useState('');
    const [extraCount, setExtraCount] = useState(0);
    const [advancing, setAdvancing]   = useState(false);
    const hasAutoGenerated = useRef(false);

    useEffect(() => {
        if (generatedIdeas.length === 0 && !hasAutoGenerated.current) {
            hasAutoGenerated.current = true;
            generateIdeas();
        }
    }, []);

    async function generateIdeas(appendMode = false) {
        setLoading(true);
        setError('');
        try {
            const { data: { user } } = await supabase.auth.getUser();

            // Clean + truncate to satisfy schema (max 100/300 chars per item, context max 490 chars)
            const cleanPillars = contentPillars
                .filter(s => s && s.trim().length > 0)
                .map(s => s.slice(0, 98))
                .slice(0, 10);
            const cleanFAQs = sessionFAQs
                .filter(s => s && s.trim().length > 0)
                .map(s => s.slice(0, 298))
                .slice(0, 15);
            const rawCtx = `${cleanPillars.join(', ')} | FAQs: ${cleanFAQs.slice(0, 5).join('. ')}`;
            const context = rawCtx.trim().slice(0, 490) || 'Creador de contenido para redes sociales';

            const res = await fetch('/api/generate-ideas', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    context,
                    platforms: ['Reels', 'TikTok', 'YouTube Shorts'],
                    goal: timeHorizon === '2weeks' ? 'Contenido para 2 semanas' : 'Contenido para 1 mes',
                    count: 24,
                    userId: user?.id,
                    projectId,
                    contentPillars: cleanPillars,
                    sessionFAQs: cleanFAQs,
                }),
            });

            if (res.status === 402) {
                window.dispatchEvent(new CustomEvent('show-no-credits'));
                return;
            }
            if (!res.ok) {
                const e = await res.json();
                throw new Error(e.error || 'Error al generar ideas.');
            }

            const { ideas } = await res.json();
            if (appendMode) {
                // Append new ideas without losing selections
                dispatch({ type: 'SET_IDEAS', payload: [...generatedIdeas, ...ideas] });
            } else {
                // First load: replace everything and reset selections
                dispatch({ type: 'SET_IDEAS', payload: ideas });
                dispatch({ type: 'SET_SELECTED_SLOTS', payload: [] });
            }
        } catch (e) {
            console.error('[Step2] generateIdeas error:', e);
            setError(e.message);
        } finally {
            setLoading(false);
        }
    }

    async function handleGenerateMore() {
        if (extraCount >= 2) return;
        setExtraCount(c => c + 1);
        await generateIdeas(true); // appendMode — keeps selections
    }

    async function handleAdvance() {
        if (selectedSlotIds.length < 2 || advancing) return;
        setAdvancing(true);
        setError('');

        try {
            const { data: { user } } = await supabase.auth.getUser();

            // Build selected ideas — only columns that exist in content_slots
            const toInsert = generatedIdeas
                .filter((_, idx) => selectedSlotIds.includes(String(idx)))
                .map(idea => ({
                    user_id:          user.id,
                    project_id:       projectId || null,
                    idea_title:       idea.titulo || 'Sin título',
                    idea_description: [
                        idea.descripcion || '',
                        idea.hook  ? `Hook: ${idea.hook}` : '',
                        idea.pilar ? `Pilar: ${idea.pilar}` : '',
                        idea.cta   ? `CTA: ${idea.cta}` : '',
                    ].filter(Boolean).join('\n'),
                    content_type:     idea.tipo || 'Educativo',
                    platform:         'Reels',
                    goal:             'engagement',
                }));

            const { data: insertedSlots, error: insertErr } = await supabase
                .from('content_slots')
                .insert(toInsert)
                .select();

            if (insertErr) throw insertErr;

            const realSlotIds = (insertedSlots || []).map(s => s.id);

            // Update context: replace index-based selection with real DB UUIDs
            dispatch({ type: 'SET_IDEAS',          payload: insertedSlots || generatedIdeas });
            dispatch({ type: 'SET_SELECTED_SLOTS', payload: realSlotIds });

            await completeStep(2, { selected_slot_ids: realSlotIds });
        } catch (e) {
            console.error('[Step2] advance error:', e);
            setError(e.message);
        } finally {
            setAdvancing(false);
        }
    }

    // Group ideas by pilar for display
    const byPilar = generatedIdeas.reduce((acc, idea, idx) => {
        const key = idea.pilar || 'General';
        if (!acc[key]) acc[key] = [];
        acc[key].push({ ...idea, _idx: String(idx) });
        return acc;
    }, {});

    const selected = selectedSlotIds.length;
    const canAdvance = selected >= 2;

    if (loading) {
        return (
            <div style={{ textAlign: 'center', padding: '64px 24px' }}>
                <Loader2 size={40} style={{ color: '#7ECECA', animation: 'spin 1s linear infinite', marginBottom: '20px' }} />
                <p style={{ color: '#aaa', fontWeight: 700, marginBottom: '6px' }}>Generando ideas para tu nicho...</p>
                <p style={{ color: '#666', fontSize: '0.85rem' }}>Usando tus pilares y FAQs para personalizar cada idea.</p>
                <style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
            </div>
        );
    }

    return (
        <div>
            {/* Header */}
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '6px', gap: '16px', flexWrap: 'wrap' }}>
                <div>
                    <h2 style={{ fontSize: '1.65rem', fontWeight: 900, marginBottom: '6px' }}>💡 Elige tus ideas</h2>
                    <p style={{ color: '#888' }}>Selecciona entre 2 y 8 ideas para guionizar.</p>
                </div>
                <button onClick={handleGenerateMore} disabled={extraCount >= 2 || loading} style={{
                    display: 'inline-flex', alignItems: 'center', gap: '6px',
                    background: extraCount >= 2 ? 'rgba(255,255,255,0.03)' : 'rgba(126,206,202,0.08)',
                    color: extraCount >= 2 ? '#444' : '#7ECECA',
                    border: `1px solid ${extraCount >= 2 ? 'rgba(255,255,255,0.08)' : 'rgba(126,206,202,0.2)'}`,
                    borderRadius: '10px', padding: '9px 16px', fontSize: '0.83rem',
                    fontWeight: 700, cursor: extraCount >= 2 ? 'not-allowed' : 'pointer',
                    flexShrink: 0,
                }}>
                    <Sparkles size={14} />
                    {extraCount >= 2 ? 'Máximo alcanzado' : `Generar más (${2 - extraCount} disponibles)`}
                </button>
            </div>

            {/* Selection counter */}
            <div style={{
                marginBottom: '24px', padding: '10px 14px',
                background: canAdvance ? 'rgba(16,185,129,0.06)' : 'rgba(255,255,255,0.03)',
                border: `1px solid ${canAdvance ? 'rgba(16,185,129,0.2)' : 'rgba(255,255,255,0.07)'}`,
                borderRadius: '10px', fontSize: '0.83rem',
                color: canAdvance ? '#10B981' : '#666',
                display: 'flex', alignItems: 'center', gap: '8px',
            }}>
                <CheckCircle2 size={15} />
                {selected === 0
                    ? 'Haz clic en las ideas que quieras grabar — mínimo 2.'
                    : selected === 1
                        ? '1 seleccionada — necesitas al menos 2 para continuar.'
                        : `${selected} seleccionadas ${selected > 8 ? '(máximo 8 recomendado)' : '— ¡listas para guionizar!'}`
                }
            </div>

            {error && (
                <div style={{ marginBottom: '20px' }}>
                    <div style={{ padding: '12px 16px', background: 'rgba(239,68,68,0.1)', borderRadius: '10px', color: '#EF4444', fontSize: '0.88rem', marginBottom: '10px' }}>
                        {error}
                    </div>
                    <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                        <button
                            onClick={async () => {
                                // Reset step in session so step 1 is shown again
                                const { data: { user } } = await supabase.auth.getUser();
                                if (user) {
                                    await supabase.from('sessions')
                                        .update({ current_step: 1, status: 'active' })
                                        .eq('id', sessionId);
                                }
                                dispatch({ type: 'SET_STEP', payload: 1 });
                            }}
                            style={{ display:'inline-flex', alignItems:'center', gap:'6px', background:'rgba(255,255,255,0.05)', color:'rgba(255,255,255,0.6)', border:'1px solid rgba(255,255,255,0.1)', borderRadius:'10px', padding:'9px 16px', fontSize:'0.82rem', fontWeight:600, cursor:'pointer' }}
                        >
                            ← Volver al Paso 1
                        </button>
                        <button
                            onClick={() => { setError(''); generateIdeas(); }}
                            style={{ display:'inline-flex', alignItems:'center', gap:'6px', background:'rgba(126,206,202,0.1)', color:'#7ECECA', border:'1px solid rgba(126,206,202,0.2)', borderRadius:'10px', padding:'9px 16px', fontSize:'0.82rem', fontWeight:600, cursor:'pointer' }}
                        >
                            <Sparkles size={13} /> Reintentar
                        </button>
                    </div>
                </div>
            )}

            {/* Ideas grouped by pilar */}
            {Object.entries(byPilar).map(([pilar, ideas]) => (
                <div key={pilar} style={{ marginBottom: '28px' }}>
                    <div style={{
                        fontSize: '0.7rem', color: '#7ECECA', fontWeight: 700,
                        textTransform: 'uppercase', letterSpacing: '.08em',
                        marginBottom: '10px', display: 'flex', alignItems: 'center', gap: '8px',
                    }}>
                        <div style={{ height: '1px', flex: 1, background: 'rgba(126,206,202,0.15)' }} />
                        {pilar}
                        <div style={{ height: '1px', flex: 1, background: 'rgba(126,206,202,0.15)' }} />
                    </div>

                    <div style={{ display: 'grid', gap: '8px' }}>
                        {ideas.map(idea => {
                            const isSelected = selectedSlotIds.includes(idea._idx);
                            return (
                                <div
                                    key={idea._idx}
                                    onClick={() => dispatch({ type: 'TOGGLE_SLOT', payload: idea._idx })}
                                    style={{
                                        padding: '14px 16px', borderRadius: '12px', cursor: 'pointer',
                                        transition: 'all 0.18s ease',
                                        background: isSelected ? 'rgba(126,206,202,0.08)' : 'rgba(255,255,255,0.025)',
                                        border: `1px solid ${isSelected ? 'rgba(126,206,202,0.35)' : 'rgba(255,255,255,0.06)'}`,
                                        display: 'flex', gap: '14px', alignItems: 'flex-start',
                                    }}
                                    onMouseEnter={e => !isSelected && (e.currentTarget.style.borderColor = 'rgba(255,255,255,0.12)')}
                                    onMouseLeave={e => !isSelected && (e.currentTarget.style.borderColor = 'rgba(255,255,255,0.06)')}
                                >
                                    <CheckCircle2
                                        size={20}
                                        style={{ flexShrink: 0, marginTop: '2px', transition: 'all 0.18s' }}
                                        color={isSelected ? '#7ECECA' : '#333'}
                                        fill={isSelected ? 'rgba(126,206,202,0.2)' : 'transparent'}
                                    />
                                    <div style={{ flex: 1 }}>
                                        <div style={{ fontWeight: 700, marginBottom: '4px', fontSize: '0.93rem', color: isSelected ? '#fff' : '#ddd' }}>
                                            {idea.titulo}
                                        </div>
                                        <div style={{ fontSize: '0.8rem', color: '#777', lineHeight: 1.5 }}>
                                            {idea.hook}
                                        </div>
                                        <div style={{ marginTop: '6px', display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                                            {idea.tipo && (
                                                <span style={{ fontSize: '0.7rem', padding: '2px 8px', borderRadius: '20px', background: 'rgba(124,58,237,0.1)', color: '#a78bfa', fontWeight: 600 }}>
                                                    {idea.tipo}
                                                </span>
                                            )}
                                            {idea.pilar && (
                                                <span style={{ fontSize: '0.7rem', padding: '2px 8px', borderRadius: '20px', background: 'rgba(255,255,255,0.04)', color: '#555', fontWeight: 600 }}>
                                                    {idea.pilar}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            ))}

            {/* Advance button */}
            <div style={{ marginTop: '8px', paddingTop: '24px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                <button onClick={handleAdvance} disabled={!canAdvance || advancing} style={{
                    display: 'inline-flex', alignItems: 'center', gap: '10px',
                    background: canAdvance ? 'var(--accent-gradient)' : 'rgba(255,255,255,0.05)',
                    color: canAdvance ? 'black' : '#555',
                    border: 'none', borderRadius: '14px', padding: '15px 30px',
                    fontSize: '0.95rem', fontWeight: 900,
                    cursor: canAdvance && !advancing ? 'pointer' : 'not-allowed',
                }}>
                    {advancing
                        ? <><Loader2 size={18} style={{ animation: 'spin 1s linear infinite' }} /> Guardando...</>
                        : <>Generar guiones para {selected} idea{selected !== 1 ? 's' : ''} <ChevronRight size={20} /></>
                    }
                </button>
                {canAdvance && (
                    <p style={{ fontSize: '0.75rem', color: '#555', marginTop: '10px' }}>
                        Se generará 1 guion por idea seleccionada. Podrás editarlos y humanizarlos en el siguiente paso.
                    </p>
                )}
            </div>

            <style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
        </div>
    );
}
